/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.93
 * Generated at: 2024-09-13 08:39:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class writeForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>회원가입Form</title>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("\n");
      out.write("body {\n");
      out.write("	background-color: #0d0d0d;\n");
      out.write("	color: #00ffcc;\n");
      out.write("}\n");
      out.write("\n");
      out.write("table {\n");
      out.write("	border-collapse: collapse;\n");
      out.write("}\n");
      out.write("th, td {\n");
      out.write("	padding: 5px;\n");
      out.write("}\n");
      out.write("div {\n");
      out.write("	color: red;\n");
      out.write("	font-size: 8pt;\n");
      out.write("	font-weight: bold;\n");
      out.write("}\n");
      out.write("h1 {\n");
      out.write("	text-align: center;\n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/projectMVC2/css/memberWritecss.css\">\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/jsp/nav.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("<h1>\n");
      out.write("	<img src=\"projectMVC2/image/4.jpg\" width=\"100\" height=\"100\" alt=\"홈\" \n");
      out.write("		 onclick=\"location.href='/projectMVC2/index.do'\" style=\"cursor: pointer;\"> \n");
      out.write("		 회원가입\n");
      out.write("</h1>\n");
      out.write("<form name=\"writeForm\" method=\"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/write.do\">\n");
      out.write("	<table border=\"1\">\n");
      out.write("		<tr>\n");
      out.write("	        <th width=\"100\">이름</th>\n");
      out.write("	        <td>\n");
      out.write("	        	<input type=\"text\" name=\"name\" id=\"name\" placeholder=\"이름 입력\">\n");
      out.write("	        	<div id=\"nameDiv\"></div>\n");
      out.write("	        </td>\n");
      out.write("	    </tr>\n");
      out.write("	    \n");
      out.write("	    <tr>\n");
      out.write("	        <th>아이디</th>\n");
      out.write("	        <td>\n");
      out.write("	        	<input type=\"text\" name=\"id\" id=\"id\" size=\"30\" placeholder=\"아이디 입력\">\n");
      out.write("	        	<input type=\"hidden\" id=\"check\" value=\"\">\n");
      out.write("	        	<div id=\"idDiv\"></div>\n");
      out.write("	        </td>\n");
      out.write("	    </tr>\n");
      out.write("	    \n");
      out.write("	    <tr>\n");
      out.write("	        <th>비밀번호</th>\n");
      out.write("	        <td>\n");
      out.write("	        	<input type=\"password\" name=\"pwd\" id=\"pwd\" size=\"40\" placeholder=\"비밀번호 입력\">\n");
      out.write("	        	<div id=\"pwdDiv\"></div>\n");
      out.write("	        </td>\n");
      out.write("	    </tr>\n");
      out.write("	    \n");
      out.write("	    <tr>\n");
      out.write("	        <th>재확인</th>\n");
      out.write("	        <td>\n");
      out.write("	        	<input type=\"password\" id=\"repwd\" size=\"40\" placeholder=\"비밀번호 입력\">\n");
      out.write("	        </td>\n");
      out.write("	    </tr>\n");
      out.write("	    \n");
      out.write("	    <tr>\n");
      out.write("	        <th>성별</th>\n");
      out.write("	        <td>\n");
      out.write("	        	<input type=\"radio\" name=\"gender\" value=\"0\" checked=\"checked\" />남자\n");
      out.write("	            <input type=\"radio\" name=\"gender\" value=\"1\" />여자\n");
      out.write("	        </td>\n");
      out.write("	    </tr>\n");
      out.write("	    \n");
      out.write("	    <tr>\n");
      out.write("	        <th>이메일</th>\n");
      out.write("	        <td>\n");
      out.write("	        	<input type=\"email\" name=\"email1\">\n");
      out.write("	        	@\n");
      out.write("	        	<input type=\"text\" name=\"email2\" id=\"email2\">\n");
      out.write("	        	\n");
      out.write("	        	<input type=\"email\" name=\"email3\" id=\"email3\" list=\"email3_list\" oninput=\"change()\">        \n");
      out.write("	        	<datalist id=\"email3_list\">\n");
      out.write("	        		<option value=\"직접입력\"></option>\n");
      out.write("	                <option value=\"naver.com\"/>\n");
      out.write("	                <option value=\"gmail.com\"/>\n");
      out.write("	                <option value=\"daum.net\"/>\n");
      out.write("	        	</datalist>\n");
      out.write("	        </td>\n");
      out.write("	    </tr>\n");
      out.write("	    \n");
      out.write("	    <tr>\n");
      out.write("	        <th>휴대전화</th>\n");
      out.write("	        <td>\n");
      out.write("	            <select name=\"tel1\">\n");
      out.write("	                <optgroup label=\"hp\">\n");
      out.write("	                    <option value=\"010\">010</option>\n");
      out.write("	                    <option value=\"011\">011</option>\n");
      out.write("	                    <option value=\"019\">019</option>\n");
      out.write("	                </optgroup>\n");
      out.write("	            </select>\n");
      out.write("		         -\n");
      out.write("		         <input type=\"text\" name=\"tel2\" size=\"4\" maxlength=\"4\">\n");
      out.write("		         -\n");
      out.write("		         <input type=\"text\" name=\"tel3\" size=\"4\" maxlength=\"4\">\n");
      out.write("			</td>\n");
      out.write("	    </tr>\n");
      out.write("	    \n");
      out.write("	    <tr>\n");
      out.write("	    	<th>주소</th>\n");
      out.write("	    	<td>\n");
      out.write("	    		<input type=\"text\" name=\"zipcode\" id=\"zipcode\" size=\"6\" readonly placeholder=\"우편번호\">\n");
      out.write("	    		<button type=\"button\" onclick=\"checkPost(); return false;\">우편번호 검색</button><br/>\n");
      out.write("	    		<input type=\"text\" name=\"addr1\" id=\"addr1\" size=\"60\" readonly placeholder=\"주소\"><br/>\n");
      out.write("	    		<input type=\"text\" name=\"addr2\" id=\"addr2\" size=\"60\" placeholder=\"상세주소\">\n");
      out.write("	    	</td>\n");
      out.write("	    </tr>\n");
      out.write("	    \n");
      out.write("	    <tr>\n");
      out.write("	    	<td colspan=\"2\" align=\"center\">\n");
      out.write("	    		<input type=\"button\" value=\"회원가입\" onclick=\"checkWrite()\"/>\n");
      out.write("	    		<input type=\"reset\" value=\"다시작성\" />\n");
      out.write("	    	</td>\n");
      out.write("	    </tr>\n");
      out.write("	</table>\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-3.7.1.min.js\"></script>\n");
      out.write("<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\n");
      out.write("<script src=\"../js/member.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
