/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.93
 * Generated at: 2024-10-18 07:36:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.inquiry;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.PrintWriter;

public final class inquiryWrite_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1729142299852L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.io.PrintWriter");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("   <meta charset=\"UTF-8\">\r\n");
      out.write("   <title>호텔 C&S - Q&A</title>\r\n");
      out.write("   <script type=\"text/javascript\" src=\"script/script.js\"></script>\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width\", initial-scale=\"1\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"/SpringHotel/resources/css/bootstrap.css\">\r\n");
      out.write("   <link rel=\"stylesheet\" href=\"/SpringHotel/resources/css/inquiryCSS.css\">\r\n");
      out.write("   <link rel=\"stylesheet\" href=\"/SpringHotel/resources/css/custom.css\">\r\n");
      out.write("   \r\n");
      out.write("      <style>\r\n");
      out.write("      #btn{\r\n");
      out.write("         margin-top:15px;\r\n");
      out.write("         margin-bottom:15px;\r\n");
      out.write("         background-color: #382f24;\r\n");
      out.write("          width:120px;\r\n");
      out.write("          height:50px;\r\n");
      out.write("          border: none;\r\n");
      out.write("          font-size:medium;\r\n");
      out.write("          color:#f1ebd5;\r\n");
      out.write("         }\r\n");
      out.write("   </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("   <nav class=\"navbar navbar-default\">\r\n");
      out.write("      <div class=\"navbar-header\">\r\n");
      out.write("            <button type=\"button\" class=\"navbar-toggle collapsed\"\r\n");
      out.write("               data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\"\r\n");
      out.write("               aria-expanded=\"false\">\r\n");
      out.write("               <span class=\"icon-bar\"></span>\r\n");
      out.write("               <span class=\"icon-bar\"></span>\r\n");
      out.write("               <span class=\"icon-bar\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"main.jsp\">HOTEL C&S</a>\r\n");
      out.write("         </div>\r\n");
      out.write("          <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("            <ul class=\"nav navbar-nav\">\r\n");
      out.write("               <li><a href=\"main.jsp\">HOME</a></li>\r\n");
      out.write("                <li><a href=\"Standard.jsp\">객실 정보</a></li>\r\n");
      out.write("               <li><a href=\"reservation1.jsp\">예약</a></li>\r\n");
      out.write("               <li><a href=\"check.jsp\">예약내역</a></li>\r\n");
      out.write("               <li class=\"active\"><a href=\"inquiryList.jsp\">Q&A</a></li>\r\n");
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("               <li class=\"dropdown\">\r\n");
      out.write("                     <a href=\"#\" class=\"dropdown-toggle\"\r\n");
      out.write("                        data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\"\r\n");
      out.write("                        aria-expanded=\"false\">접속하기<span class=\"caret\"></span></a>\r\n");
      out.write("                    <ul class=\"dropdown-menu\">\r\n");
      out.write("                        <li class=\"active\"><a href=\"login.jsp\">로그인</a></li>\r\n");
      out.write("                        <li><a href=\"join.jsp\">회원가입</a></li>\r\n");
      out.write("                     </ul>\r\n");
      out.write("               </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("         </div> \r\n");
      out.write("   </nav>\r\n");
      out.write("   \r\n");
      out.write("   <br/><br />\r\n");
      out.write("	<div id=\"detailcomment\">\r\n");
      out.write("	   호텔 C&S는 언제나 고객님의 목소리에 귀기울이고 있습니다.<br />\r\n");
      out.write("	   고객님들의 소중한 충고와 격려, 또는 제안의 말씀을 주시면 더 나은 서비스로 보답하겠습니다.\r\n");
      out.write("	</div>   \r\n");
      out.write("	<form name=\"regForm\" id=\"regForm\" method=\"post\">\r\n");
      out.write("	    <table align=\"center\" class=\"inquiryDetail\">\r\n");
      out.write("	        <tr>\r\n");
      out.write("	            <td id=\"detail\" style=\"background-color: #EEEEEE;\">TITLE</td>\r\n");
      out.write("	            <td>\r\n");
      out.write("	                <select name=\"qtypesId\" id=\"qtypesId\">\r\n");
      out.write("	                    <option value=\"1\">문의</option> <!-- 실제 ID로 수정 -->\r\n");
      out.write("	                    <option value=\"2\">신청</option>\r\n");
      out.write("	                    <option value=\"3\">불만</option>\r\n");
      out.write("	                    <option value=\"4\">건의</option>\r\n");
      out.write("	                    <option value=\"5\">기타</option>\r\n");
      out.write("	                </select>\r\n");
      out.write("	            </td>\r\n");
      out.write("	        </tr>\r\n");
      out.write("	        <tr>\r\n");
      out.write("	            <td id=\"detail\" style=\"background-color: #EEEEEE;\">CONTENT</td>\r\n");
      out.write("	            <td><textarea name=\"b_content\" rows=\"20\" cols=\"150\" id=\"content\" placeholder=\"내용을 입력하세요.\"></textarea></td>\r\n");
      out.write("	        </tr>\r\n");
      out.write("	        <tr align=\"center\">\r\n");
      out.write("	            <td colspan=\"2\">\r\n");
      out.write("	                <input type=\"button\" id=\"btn\" value=\"확인\" />\r\n");
      out.write("	                <input type=\"reset\" id=\"btn\" value=\"취소\" />\r\n");
      out.write("	            </td>\r\n");
      out.write("	        </tr>\r\n");
      out.write("	    </table>\r\n");
      out.write("	</form>\r\n");
      out.write("   <script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("   <script src=\"/SpringHotel/resources/js/bootstrap.js\"></script>\r\n");
      out.write("   <script src=\"/SpringHotel/resources/js/admin.js\"></script>\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("	<div id=\"footer-logo\">\r\n");
      out.write("		<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\"><img src=\"/SpringHotel/resources/image/sh.png\" width=\"200\" height=\"180\" alt=\"HOME\"></a>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div id=\"footer-info\">\r\n");
      out.write("		<b>(주)Spring Hotel 02-1234-5678</b><br/>\r\n");
      out.write("		000-000 충청남도 아산시 순천향로 25-14<br/>\r\n");
      out.write("		Email : Spring@hotel.com<br>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div id=\"footer-service\">\r\n");
      out.write("		Hours<br/>\r\n");
      out.write("		호텔서비스<br/>\r\n");
      out.write("	    00:00 ~ 24:00\r\n");
      out.write("	    객실예약(주중)<br/>\r\n");
      out.write("        09:00 ~ 18:00<br/>\r\n");
      out.write("        업무시간 외에는온라인 예약을 이용해주시기 바랍니다.\r\n");
      out.write("	</div>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
