---- 기존 테이블 삭제
--DROP TABLE BOARD CASCADE CONSTRAINTS;
--DROP TABLE MEMBER CASCADE CONSTRAINTS;
--DROP TABLE members CASCADE CONSTRAINTS;
--DROP TABLE posts CASCADE CONSTRAINTS;
--
---- 기존 시퀀스 삭제
--DROP SEQUENCE BOARD_SEQ;


-- MEMBER 테이블 생성
CREATE TABLE MEMBER (
    MEMBER_ID VARCHAR2(50) PRIMARY KEY,  -- 회원 ID (고유)
    NAME VARCHAR2(100) NOT NULL,         -- 회원 이름
    EMAIL VARCHAR2(100) NOT NULL UNIQUE, -- 이메일 (고유)
    PASSWORD VARCHAR2(100) NOT NULL,     -- 비밀번호
    REGISTER_DATE DATE DEFAULT SYSDATE   -- 가입일 (기본값: 현재 날짜)
);

-- BOARD 테이블 생성
CREATE TABLE BOARD (
    SEQ NUMBER PRIMARY KEY,                  -- 게시글 번호 (고유)
    MEMBER_ID VARCHAR2(50) REFERENCES MEMBER(MEMBER_ID), -- 작성자 ID (외래 키)
    SUBJECT VARCHAR2(200) NOT NULL,          -- 게시글 제목
    CONTENT CLOB NOT NULL,                   -- 게시글 내용
    LOGTIME DATE DEFAULT SYSDATE             -- 작성일 (기본값: 현재 날짜)
);

-- BOARD 테이블용 시퀀스 생성
CREATE SEQUENCE BOARD_SEQ
START WITH 1
INCREMENT BY 1;

-- COMMENTS 테이블 생성 (게시글에 대한 댓글을 저장)
CREATE TABLE COMMENTS (
    COMMENT_ID NUMBER PRIMARY KEY,                 -- 댓글 ID (고유)
    POST_ID NUMBER REFERENCES BOARD(SEQ),          -- 게시글 ID (BOARD 테이블과 외래 키 관계)
    MEMBER_ID VARCHAR2(50) REFERENCES MEMBER(MEMBER_ID), -- 댓글 작성자 ID (MEMBER 테이블과 외래 키 관계)
    CONTENT CLOB NOT NULL,                         -- 댓글 내용
    LOGTIME DATE DEFAULT SYSDATE                   -- 작성일 (기본값: 현재 날짜)
);

-- COMMENTS 테이블용 시퀀스 생성
CREATE SEQUENCE COMMENTS_SEQ
START WITH 1
INCREMENT BY 1;

-- 조회수 추가
ALTER TABLE BOARD ADD VIEWS NUMBER DEFAULT 0;

-- 모든 댓글 조회 (게시글별로 조회)
SELECT * FROM COMMENTS WHERE POST_ID = ? ORDER BY COMMENT_ID ASC;

-- 모든 회원 조회
SELECT * FROM MEMBER;

-- 모든 게시글 조회
SELECT * FROM BOARD ORDER BY SEQ DESC;





